In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv(r"C:\Users\mahen\Downloads\SmartCity_Citizen_Issues_Dirty.csv")

In [3]:
df

,Citizen_ID,Area_Sector,Issue_Type,Complaint_Text,Severity_Level,Reported_Time,Resolution_Time_Hours,Assigned_Department,Satisfaction_Rating,Followup_Required,Latitude,Longitude,AI_Priority_Score
0,C1000,C2,Garbge,Leave past space behind almost same million re...,Hi,09-07-2025 23:27,54.0,Clean Dept,4.0,Yes,19.253373,72.905014,0.20
1,C1001,A1,WiFiIssu,They above story will similar member message s...,NaN,24-07-2025 04:23,999.0,Elect Dept,1.0,Yes,19.002650,73.032622,0.77
2,C1002,C1,Trafic,Five stage clear discuss training long go char...,Critcal,13-02-2025 08:51,84.0,SmartWifiDept,2.0,Yes,19.253647,72.963361,0.16
3,C1003,A1,WiFiIssu,Certain maintain effect after official produce...,Lo,10-02-2025 20:31,114.0,Watr Dept,2.0,Yes,19.019061,72.903798,0.48
4,C1004,D1,Trafic,Prepare stand enjoy kind memory purpose carry ...,Lo,05-11-2025 23:16,999.0,Watr Dept,4.0,No,19.051554,73.018950,0.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1045,C1574,A1,WiFiIssu,Onto challenge federal fear debate total democ...,NaN,06-12-2025 15:31,NaN,Elect Dept,2.0,No,19.131479,72.801426,0.26
1046,C1255,A1,Trafic,Light card argue fire wish fact mouth.,Med,14-01-2025 00:51,10.0,NaN,NaN,No,19.222672,73.072073,0.25
1047,C1982,A1,Trafic,Real information picture edge among home nothi...,Hi,28-09-2025 10:30,13.0,Clean Dept,1.0,Yes,19.228772,72.881210,0.88
1048,C1678,B1,Pothl,Book behind similar certainly window pick majo...,Critcal,22-05-2025 10:51,51.0,Road Dept,5.0,No,19.293064,72.937294,0.45
1049,C1506,C2,Stret Light,Meeting voice run face loss purpose probably c...,Med,23-09-2025 05:56,44.0,Watr Dept,NaN,No,19.113687,72.966615,0.36

In [4]:
df.shape

(1050, 13)

In [5]:
df.info

<bound method DataFrame.info of      Citizen_ID Area_Sector   Issue_Type  \
0         C1000          C2       Garbge
1         C1001          A1     WiFiIssu
2         C1002          C1       Trafic
3         C1003          A1     WiFiIssu
4         C1004          D1       Trafic
...         ...         ...          ...
1045      C1574          A1     WiFiIssu
1046      C1255          A1       Trafic
1047      C1982          A1       Trafic
1048      C1678          B1        Pothl
1049      C1506          C2  Stret Light

                                         Complaint_Text Severity_Level  \
0     Leave past space behind almost same million re...             Hi
1     They above story will similar member message s...            NaN
2     Five stage clear discuss training long go char...        Critcal
3     Certain maintain effect after official produce...             Lo
4     Prepare stand enjoy kind memory purpose carry ...             Lo
...                                                 ...            ...
1045  Onto challenge federal fear debate total democ...            NaN
1046             Light card argue fire wish fact mouth.            Med
1047  Real information picture edge among home nothi...             Hi
1048  Book behind similar certainly window pick majo...        Critcal
1049  Meeting voice run face loss purpose probably c...            Med

         Reported_Time  Resolution_Time_Hours Assigned_Department  \
0     09-07-2025 23:27                   54.0          Clean Dept
1     24-07-2025 04:23                  999.0          Elect Dept
2     13-02-2025 08:51                   84.0       SmartWifiDept
3     10-02-2025 20:31                  114.0           Watr Dept
4     05-11-2025 23:16                  999.0           Watr Dept
...                ...                    ...                 ...
1045  06-12-2025 15:31                    NaN          Elect Dept
1046  14-01-2025 00:51                   10.0                 NaN
1047  28-09-2025 10:30                   13.0          Clean Dept
1048  22-05-2025 10:51                   51.0           Road Dept
1049  23-09-2025 05:56                   44.0           Watr Dept

      Satisfaction_Rating Followup_Required   Latitude  Longitude  \
0                     4.0               Yes  19.253373  72.905014
1                     1.0               Yes  19.002650  73.032622
2                     2.0               Yes  19.253647  72.963361
3                     2.0               Yes  19.019061  72.903798
4                     4.0                No  19.051554  73.018950
...                   ...               ...        ...        ...
1045                  2.0                No  19.131479  72.801426
1046                  NaN                No  19.222672  73.072073
1047                  1.0               Yes  19.228772  72.881210
1048                  5.0                No  19.293064  72.937294
1049                  NaN                No  19.113687  72.966615

      AI_Priority_Score
0                  0.20
1                  0.77
2                  0.16
3                  0.48
4                  0.06
...                 ...
1045               0.26
1046               0.25
1047               0.88
1048               0.45
1049               0.36

[1050 rows x 13 columns]>

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Citizen_ID             1050 non-null   object
 1   Area_Sector            1050 non-null   object
 2   Issue_Type             1050 non-null   object
 3   Complaint_Text         1050 non-null   object
 4   Severity_Level         946 non-null    object
 5   Reported_Time          1050 non-null   object
 6   Resolution_Time_Hours  944 non-null    float64
 7   Assigned_Department    947 non-null    object
 8   Satisfaction_Rating    947 non-null    float64
 9   Followup_Required      1050 non-null   object
 10  Latitude               1050 non-null   float64
 11  Longitude              1050 non-null   float64
 12  AI_Priority_Score      1050 non-null   float64
dtypes: float64(5), object(8)
memory usage: 106.8+ KB

In [7]:
df.describe()

,Resolution_Time_Hours,Satisfaction_Rating,Latitude,Longitude,AI_Priority_Score
count,944.000000,947.000000,1050.000000,1050.000000,1050.000000
mean,83.066737,3.168955,19.150080,72.951222,0.519790
std,142.336974,1.735394,0.085401,0.087381,0.281351
min,1.000000,1.000000,19.000494,72.800127,0.000000
25%,34.000000,2.000000,19.078544,72.877514,0.280000
50%,63.500000,3.000000,19.150807,72.952266,0.530000
75%,94.000000,4.000000,19.221699,73.026137,0.750000
max,999.000000,10.000000,19.299635,73.099859,1.000000

In [8]:
df.isnull().sum()

Citizen_ID                 0
Area_Sector                0
Issue_Type                 0
Complaint_Text             0
Severity_Level           104
Reported_Time              0
Resolution_Time_Hours    106
Assigned_Department      103
Satisfaction_Rating      103
Followup_Required          0
Latitude                   0
Longitude                  0
AI_Priority_Score          0
dtype: int64

In [9]:
(df.isnull().sum()/len(df)*100).sort_values(ascending=False)

Resolution_Time_Hours    10.095238
Severity_Level            9.904762
Assigned_Department       9.809524
Satisfaction_Rating       9.809524
Citizen_ID                0.000000
Complaint_Text            0.000000
Issue_Type                0.000000
Area_Sector               0.000000
Reported_Time             0.000000
Followup_Required         0.000000
Latitude                  0.000000
Longitude                 0.000000
AI_Priority_Score         0.000000
dtype: float64

In [10]:
# Fill missing numerical values with median
df['Resolution_Time_Hours'].fillna(df['Resolution_Time_Hours'].median(), inplace=True)
df['Satisfaction_Rating'].fillna(df['Satisfaction_Rating'].median(), inplace=True)

# Fill missing categorical values with mode
df['Assigned_Department'].fillna(df['Assigned_Department'].mode()[0], inplace=True)
df['Severity_Level'].fillna(df['Severity_Level'].mode()[0], inplace=True)

In [11]:
# Correct Issue_Type
df['Issue_Type'] = df['Issue_Type'].replace({
    "Garbge": "Garbage",
    "Watr": "Water",
    "WiFiIssu": "WiFi Issue",
    "Pothl": "Pothole",
    "Trafic": "Traffic",
    "Stret Light": "Street Light",
    "Pollutn": "Pollution"})

# Correct Severity_Level
df['Severity_Level'] = df['Severity_Level'].replace({
    "Lo":"Low",
    "Med":"Medium",
    "Hi":"High",
    "Critcal":"Critical"})

# Correct Assigned_Department
df['Assigned_Department'] = df['Assigned_Department'].replace({
    "Watr Dept": "Water Dept",
    "Elect Dept": "Electricity Dept",
    "Road Dept": "Roads Dept",
    "SmartWifiDept": "Smart Wifi Dept",
    "Clean Dept": "Cleanliness Dept"})

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.isnull().sum()

Citizen_ID               0
Area_Sector              0
Issue_Type               0
Complaint_Text           0
Severity_Level           0
Reported_Time            0
Resolution_Time_Hours    0
Assigned_Department      0
Satisfaction_Rating      0
Followup_Required        0
Latitude                 0
Longitude                0
AI_Priority_Score        0
dtype: int64

In [17]:
# Check data types
df.dtypes

Citizen_ID                object
Area_Sector               object
Issue_Type                object
Complaint_Text            object
Severity_Level            object
Reported_Time             object
Resolution_Time_Hours    float64
Assigned_Department       object
Satisfaction_Rating      float64
Followup_Required         object
Latitude                 float64
Longitude                float64
AI_Priority_Score        float64
dtype: object

In [20]:
# Save cleaned dataset
df.to_excel("SmartCity_Cleaned.xlsx", index=False)

In [19]:
import os
os.getcwd()

'C:\\Users\\mahen'